### ISSUE TITLE
Bug with some custom components

### ISSUE THREAD

**Issue by 1RandomDev** [robinwittebol/whatsapp-theme#3]
The affected components are:
- [button-card](https://github.com/custom-cards/button-card)
- [threedy](https://github.com/dangreco/threedy)
- [mini-graph-card](https://github.com/kalkih/mini-graph-card)

![Bildschirmfoto vom 2022-03-08 18-13-41](https://user-images.githubusercontent.com/84292805/157290004-00a19dd8-52ad-4867-94d8-5fb0c9b24e24.png)

**Comment by robinwittebol** [comment]
I'm not exactly sure what causes this. Test results were inconsistent. Some of my dashboards had the issue and some didn't. Different cards were effected, some were built-in cards and some custom. 

It seemed to fixed itself after emptying the cache and refreshing a couple of times.
So it might have to do with frontend caching.

Possibly related issue: https://github.com/home-assistant/frontend/issues/10916
and PR: https://github.com/home-assistant/frontend/pull/11977

I've added the ha-card-background variable just in case.
